apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pr5kicnzy-python 
  janus-idp.io/tekton: pr5kicnzy-python
  backstage.io/kubernetes-id: pr5kicnzy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pr5kicnzy-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml