apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pr5kicnzy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pr5kicnzy-python 
  name: pr5kicnzy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pr5kicnzy-python 
